### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by Awebus** [kalwalkden/django-materializecss-form#9] opened 2016-10-21 14:32 UTC
DateInput field does not render name and id

```
class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['title', 'start_date', 'end_date' ]
        widgets = {
            'start_date': forms.DateInput(format='%Y-%m-%d', attrs={'class': 'datepicker'}),
            'end_date': forms.DateInput(format='%Y-%m-%d', attrs={'class': 'datepicker'}),
        }
```

**Comment by florent1933** [comment] 2016-10-23 21:54
Please check if the issue already exists before open a new one.

This is a duplicate of: https://github.com/florent1933/django-materializecss-form/issues/7

**Closed as completed by florent1933** 2016-10-23 21:54 UTC
